name: ci

on:
  push:
    branches:
      - main

jobs:
  determine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: cheese
        run: |
          cd cheeses/
          CHEESES=$(find * -type d -exec echo \"{}\" \; | paste -s -d, -)
          echo "::set-output name=names::[$CHEESES]"
    outputs:
     cheeses: ${{ steps.cheese.outputs.names }}
  docker-build:
    runs-on: ubuntu-latest
    needs: [determine]
    strategy:
      matrix:
        cheese: ${{ fromJSON(needs.determine.outputs.cheeses) }}
    steps:
      - uses: actions/checkout@v2
      - name: qemu_setup
        uses: docker/setup-qemu-action@v1
      - name: buildx_setup
        uses: docker/setup-buildx-action@v1
      - name: docker_login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x
          tags: boredland/cheese:${{ matrix.cheese }}
          build-args: |
            CHEESE=${{ matrix.cheese }}
