name: ci

on:
  push:
    branches:
      - main

jobs:
  determine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2
      - id: cheese
        run: |
          cd cheeses/
          CHEESES=$(find * -type d -exec echo \"{}\" \; | paste -s -d, -)
          echo "::set-output name=names::[$CHEESES]"
    outputs:
     cheeses: ${{ steps.cheese.outputs.names }}
  docker-build:
    runs-on: ubuntu-latest
    needs: [determine]
    strategy:
      matrix:
        cheese: ${{ fromJSON(needs.determine.outputs.cheeses) }}
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2
      - name: qemu_setup
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # tag=v2
      - name: buildx_setup
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # tag=v1
      - name: docker_login
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build docker image
        id: docker_build
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # tag=v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x
          tags: boredland/cheese:${{ matrix.cheese }}
          build-args: |
            CHEESE=${{ matrix.cheese }}
